site_name: SHAIPER - AI for Surrogate Modelling

site_url: https://shaiper-software.github.io/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  logo: assets/images/logo_large.png
  favicon: assets/images/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      # primary: black # override in custom.css
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      # primary: black # override in custom.css
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - navigation.footer
    - content.code.copy
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - content.code.annotate
markdown_extensions:
  - toc:
      permalink: true
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
   - with-pdf:
       enabled: false

       author: ""
       copyright: ""
        
       cover: false
       back_cover: true
       cover_title: SHAIPER - AI for Surrogate Modelling Documentation
       cover_subtitle: ""
      #  custom_template_path: TEMPLATES PATH
        
       toc_title: Table of Contents
       heading_shift: false
       toc_level: 3
       ordered_chapter_level: 2
      #  excludes_children:
      #     - 'release-notes/:upgrading'
      #     - 'release-notes/:changelog'
        
      #  exclude_pages:
      #     - 'bugs/'
      #     - 'appendix/contribute/'
      #  convert_iframe:
      #     - src: IFRAME SRC
      #       img: POSTER IMAGE URL
      #       text: ALTERNATE TEXT
      #     - src: ...
       two_columns_level: 3
        
      #  render_js: true
      #  headless_chrome_path: headless-chromium
        
      #  enabled_if_env: ENABLE_PDF_EXPORT
        
       debug_html: true
       show_anchors: true
       verbose: true
       
       output_path: shaiper_documentation.pdf

   - search: false
   - awesome-nav
   - include-markdown
   - gen-files:
      scripts:
        - docs/scripts/gen_api_pages.py
  #  - literate-nav:
  #     nav_file: SUMMARY.md   # generated by gen_api_pages.py
   - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["submodules/ai-for-surrogate-modelling"]
          options:
            docstring_style: google
            show_root_heading: true
            show_root_full_path: true
            show_signature: true
            show_source: true
            inherited_members: false
            show_signature_annotations: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
repo_url: https://code.it4i.cz/kra568/ai-surrogate-modelling
repo_name: SHAIPER - AI for Surrogate Modelling
edit_uri: null
# extra_css:
#   - css/custom.css
#   - css/mkdocstrings.css
extra:
  font:
    text: Roboto
    code: Roboto Mono